#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAw8m5SUMV1JRQtTqYxuHwmWEE5YD/FdoDcGfZuEs/bnl71cWn
    XuVxS7RsVdBjyj3aKGJGp3q7wPtl5zfPmu/hW19YvC+2r1dO2flKYs1iv6v/P8pX
    yOp8bPLnw88NhCw2vKyedAtZOCNRPXAgn06x4TXeLcGW52XljK7TcS17T8WgNgBq
    thJDImzNYk6iTeBNHEcq64PqKJ7M+1QbIJMLsVDjc1nc3+vUhykLexBAL88XBjfk
    rU3+72jNubSOuNJQikzu1x0OHeBj38ncovT64zHj6hwr39oS0wIE2hNX2hzYFYVq
    UwtpAuaRTDFu3BzZMvCh5YlunxLRkrCwnICsaQIDAQABAoIBAB/0JFFYqY9wRVvO
    nHCZH3No6iuqyfb/BeCqklYJseiN2zAgehh6yerZH3VB9YdkYN6Ga5GZ7lqorRD3
    guJ+lAEdppXQE7i6PxxEG2fUrXEq2RXIKFuaKYR+gGTsvf/8V1KjuZim4YDQAspM
    KobViSKAcCp3lfFeKAC157xo998k0LB9jfHuzmrdYwF75Ob5WmSxkiFRIFeyDUIh
    EyqzlaoMKWWEw4itw2nIpT2093wIT9+/WrZkbg8HTc/4yl/X7bg7LpHJDBPOfZpf
    jmIM6AsFEI/FqSBlC54aQPbJmlW3cCbynIE4pZta3vFGDkFsrE5LK9F1m5dlylNQ
    YydOESECgYEA7lW09P0t7YOXGjdMAe+8yLWN3cS59AYSzCsvMhmIuo3qgjMMHann
    yF+d2hswCFv2W3b01pXiX5JqgzfpPXaXVLLsgsmdQli3eQSH9AVx9QrYMI4LCIT+
    thgmXyd205lw4CCBD7KE0Q4jGOzwZ7pCeh2Qdlm0/Qt+CuqyuUnevLMCgYEA0ky1
    9N90snHwXZs9col0GEP45hHXIid3x6dmdXqHVyFxBRy70adWSHq8zs4cmXR/aZuI
    4kxJoAvfKA8ikro6qLzuhiprvg8y1x0xO3wd3+9lfHuC2hEu8KneKKP/e0UIgFMn
    4qxGGFbJWdQf6gpsVBk3t/oVnX7ec7jG28IKeHMCgYA0iPPgZMZw6mauQq4gZyXn
    4A0rayfKIGSYWJSIqJQ4+vtMQ9BR4ZfT1S/IWeHWld7R/oCtpFBH3NBZqENjZvao
    luAHXEWr0D5xEIyfP2wFJaTN3yGTeS1kGiKrKtnIfrQg00lfmmwoYMNfxSqg0q/A
    ly+2xsNcW+ImqeFHcn8EfQKBgDF+XFSFQrG8nxVos82BDBGp7ao4CKnBIC+c9kAv
    1iprdG3/lTSCbYwhVs5VM+XpxRLVyCF6UtmX8a074qclrSiJTpnE4haY/R4jgLK/
    Q0iwzvG9H86yvJlnYSGvdzFLzfRlnb17TgPsaPb7NYefbF9ej/58nRm0Aia6FhMi
    V9SBAoGAHyCGgcYUZsveZdFqiYD9lcetaehvlliv10rQ8oaqE21oIWrTMPYmdKMP
    S6PuCsesl8Rpt/4S2f6JqGPi0SYVsHWqFP/74HaMETSaMZ51NlE8shdZE6gkBH8J
    AHhKOUcJKl94fafoM8Ixdq7D7Gt8RTJZvXkLl7f8pisrnHMTYjM=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/gps_release.key
      iv_filename:  /etc/rails/keys/gps_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAuV2J0A1JZIaWxGVJZRKmsIoawxyM5+H14xQWM92vR/jCSurd
    vts7m1mXbgU7P2OLX+eF1iLW/EtxK2ItZRLrZI+sd9NHdu5GSOGlL7etRo84RQo/
    dOcoifMXnQyOK6tTBvSipOwke+U9eZCqaR9WzLS8N8VyiWx2JuaWMfB+1O9nvwCB
    gnFnmBFIgC6LOKmPNxsSNd2xacngSlApVC0uoWelAMW8+cRlbFAPa82t98ju0STC
    +bRlxJuzbxmdFXOWjmMsYQI2CrRLVcwzhSIoa5OI6UM5ZshcFlXC/zZCXFQGR9X/
    aS79HEBQqVpANz7nAEoJXYhalSqA+eJ77Ll3xQIDAQABAoIBABOzKjNPRi6F0z4a
    GZvBSK/YbZGw1hTKwewZNWbbt4YpnNSDc3+WIxaWhe5uZeaNuME/hMzGNRzpE6Tt
    sS9dvGCamFS/woeUOSoDuR+CIMsv62YC+c19x6QpjqflLrLbaV6C30oxworcSRVD
    V6kGaJ4m0x4GQO7z9PabaPjzuzb78BtoSoNP/o1ucgA5I3sHZ/ZqBeNAS9d55wBJ
    UM5RdSVX6Wl9qEwywsaQeoDXP3Z6+ib5gTXZbAUNtZnXy53g8kuLeuvih39fasOi
    Tmz6n3kJ4zDDpOQbDtmvfTcbp1Cze2UY7QTG5rQ6HBLCx38AtABbQrCg8d4TzTnA
    VW2TXyECgYEA6ZCXiUlYf1zTUt/dgEco8vbpwftojygny5o4zwpF35pXE53IEOUh
    jvtkIQDvkATBncuBov5C05RunzeczGlTDQvnOczVJLAEH4KaW+k6XXk74rW0pIB9
    MUbOqWbMPj0oo5HLxqdT94ZAAGUsMCq4oBkjQbqnll+i6FW6DkMVFS0CgYEAyyu2
    V54LkeoflXM2esiGRV4437XpWbEMLPB5hb8uAjdutPzYe9OKXBIxsLGYA37dr7SH
    9L680FLiCZxnHNdUnOX9H/6tEnXj4XeiiA9s3eNVQHBklUa9vB0IMBq3VV/dt+Nr
    up/Su/XnA9H8p30GXmMnZyhsTsaBHb+OhxnAu/kCgYAAp99FC2esM96EBQziJ1D+
    HaNaYBJTFJHICI7QRf8cOZq0+2RsZ7hIZnxJe28wwFKq1r9ubbhST8BfwhA2orUQ
    /E+R4flXOQdJ71vvliAL0yNP56KyM4omcURzRU6dfh53FxmzXRTnRQE4/w+4suYB
    zRBERvnhejNC47q5/4Y3oQKBgQCSvWGXarjkjHp/UJVanRYNZ/4f5Z1CgJNQqea7
    aNdsFmlJIw2gcasO0L0+5yXp8GlhDDzd0h1BQXusgWAf/o5IO/xUbXbHTIpoQCYN
    q0ZwBE+AmSysfElxYm6Vf9ZGPVVACWu3gNONmg9ePP4EYlKFPYwp/5IqW0jKGZ5x
    iXIg0QKBgC+FsbMtAi2ey7s+IIXkO388uosCA1qWLLykWBAkpDW55iTj3tbnoCNN
    WaozbteZ5F+6QLjetj+IGyPEK1mVvg/6mJEhTEva/14GsPPgWf2GQp860a9mHBF7
    3p9YbNQw0ecuEH3f31OAokcbdH7hyG/K5Mrp31F5gNIn/22BDWYk
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/gps_production.key
      iv_filename:  /etc/rails/keys/gps_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
